NL2BASH_SKILLS = [
    {
        "category": "file_search",
        "intent": "按文件名或扩展名查找文件",
        "patterns": ["查找", "找文件", "扩展名", "pdf", "log", "find file", "by name"],
        "command_templates": ["find . -type f -name '<pattern>'"],
        "tips": ["递归查找优先使用 find", "通配符建议用引号包裹"],
    },
    {
        "category": "file_search",
        "intent": "按修改时间查找文件",
        "patterns": ["最近", "天内", "修改", "mtime", "modified"],
        "command_templates": ["find . -type f -mtime -<days>"],
        "tips": ["-mtime -7 表示 7 天内修改过", "先用 -print 预览结果"],
    },
    {
        "category": "file_search",
        "intent": "统计匹配文件数量",
        "patterns": ["统计", "数量", "多少个", "count files", "wc"],
        "command_templates": ["find . -type f -name '<pattern>' | wc -l"],
        "tips": ["wc -l 常用于统计行数或列表条数"],
    },
    {
        "category": "file_ops",
        "intent": "列出大文件",
        "patterns": ["最大", "大文件", "largest", "top files"],
        "command_templates": ["find . -type f -printf '%s %p\\n' | sort -nr | head -n 10"],
        "tips": ["先排序再取前 N 条", "du -ah 也可用于估算目录大小"],
    },
    {
        "category": "file_ops",
        "intent": "安全删除临时文件",
        "patterns": ["删除", "临时文件", "tmp", "temporary", "clean"],
        "command_templates": ["find . -type f \\( -name '*.tmp' -o -name '*~' \\) -print"],
        "tips": ["删除前先用 -print 确认", "确认后再把 -print 改为 -delete"],
    },
    {
        "category": "file_ops",
        "intent": "批量重命名文件",
        "patterns": ["批量重命名", "rename", "改名"],
        "command_templates": ["for f in *.txt; do mv \"$f\" \"${f%.txt}.bak\"; done"],
        "tips": ["批量 mv 前建议先 echo 预览"],
    },
    {
        "category": "text_processing",
        "intent": "按关键词过滤日志",
        "patterns": ["日志", "关键词", "error", "grep", "包含"],
        "command_templates": ["grep -R \"<keyword>\" <path>"],
        "tips": ["-R 递归搜索目录", "-i 可忽略大小写"],
    },
    {
        "category": "text_processing",
        "intent": "统计包含关键词的行数",
        "patterns": ["行数", "统计", "包含", "grep count", "error"],
        "command_templates": ["grep -R \"<keyword>\" <path> | wc -l"],
        "tips": ["grep 输出匹配行，wc -l 统计行数"],
    },
    {
        "category": "text_processing",
        "intent": "按列提取文本",
        "patterns": ["按列", "第几列", "awk", "cut", "column"],
        "command_templates": ["awk '{print $1}' <file>"],
        "tips": ["awk 适合空白分隔列", "cut 适合固定分隔符"],
    },
    {
        "category": "text_processing",
        "intent": "排序去重",
        "patterns": ["去重", "排序", "sort", "uniq", "unique"],
        "command_templates": ["sort <file> | uniq -c | sort -nr"],
        "tips": ["uniq 通常要先配合 sort"],
    },
    {
        "category": "text_processing",
        "intent": "替换文件内容",
        "patterns": ["替换", "sed", "replace", "批量替换"],
        "command_templates": ["sed -i 's/<old>/<new>/g' <file>"],
        "tips": ["sed -i 会原地修改文件，建议先备份或去掉 -i 预览"],
    },
    {
        "category": "process_system",
        "intent": "查询进程",
        "patterns": ["进程", "ps", "process", "查询进程"],
        "command_templates": ["ps aux | grep '<name>'"],
        "tips": ["pgrep -af 可直接按名称查进程"],
    },
    {
        "category": "process_system",
        "intent": "查看端口占用",
        "patterns": ["端口", "占用", "8080", "port", "listen"],
        "command_templates": ["lsof -i :<port>", "ss -ltnp 'sport = :<port>'"],
        "tips": ["lsof/ss 可查看监听端口对应进程"],
    },
    {
        "category": "process_system",
        "intent": "终止进程",
        "patterns": ["杀掉", "终止", "kill", "kill process"],
        "command_templates": ["kill <pid>"],
        "tips": ["优先使用普通 kill，避免直接 kill -9"],
    },
    {
        "category": "process_system",
        "intent": "查看磁盘和目录占用",
        "patterns": ["磁盘", "目录大小", "df", "du", "disk"],
        "command_templates": ["df -h", "du -sh * | sort -hr | head -n 10"],
        "tips": ["df 查看文件系统空间", "du 查看目录或文件大小"],
    },
    {
        "category": "process_system",
        "intent": "查看内存与系统信息",
        "patterns": ["内存", "系统信息", "free", "uname", "memory"],
        "command_templates": ["free -h", "uname -a"],
        "tips": ["free -h 用人类可读单位显示内存"],
    },
    {
        "category": "network",
        "intent": "测试网络连通性",
        "patterns": ["网络", "连通", "ping", "connectivity"],
        "command_templates": ["ping -c 4 <host>"],
        "tips": ["ping 可快速判断主机是否可达"],
    },
    {
        "category": "network",
        "intent": "HTTP 请求与接口调试",
        "patterns": ["curl", "请求", "接口", "http", "api"],
        "command_templates": ["curl -I <url>", "curl -s <url>"],
        "tips": ["-I 只取响应头", "避免执行 curl 下载内容后直接 pipe 到 sh"],
    },
    {
        "category": "network",
        "intent": "DNS 查询",
        "patterns": ["dns", "域名", "nslookup", "dig"],
        "command_templates": ["nslookup <domain>", "dig <domain>"],
        "tips": ["dig 输出更详细，nslookup 更常见"],
    },
    {
        "category": "network",
        "intent": "下载文件",
        "patterns": ["下载", "wget", "download"],
        "command_templates": ["wget <url>", "curl -O <url>"],
        "tips": ["下载后先检查文件来源和内容"],
    },
    {
        "category": "permissions_users",
        "intent": "查看当前用户身份",
        "patterns": ["当前用户", "whoami", "id", "用户"],
        "command_templates": ["whoami", "id"],
        "tips": ["id 可显示 uid、gid 和所属组"],
    },
    {
        "category": "permissions_users",
        "intent": "修改权限",
        "patterns": ["权限", "chmod", "可执行", "permission"],
        "command_templates": ["chmod +x <file>"],
        "tips": ["递归 chmod 和 777 风险较高，应缩小范围"],
    },
    {
        "category": "permissions_users",
        "intent": "修改所有者",
        "patterns": ["所有者", "chown", "owner"],
        "command_templates": ["sudo chown <user>:<group> <path>"],
        "tips": ["递归 chown 可能破坏系统权限"],
    },
    {
        "category": "archive",
        "intent": "创建压缩归档",
        "patterns": ["压缩", "打包", "tar", "zip", "archive"],
        "command_templates": ["tar -czf archive.tar.gz <path>", "zip -r archive.zip <path>"],
        "tips": ["tar.gz 适合 Linux 归档", "zip 跨平台更常见"],
    },
    {
        "category": "archive",
        "intent": "解压归档",
        "patterns": ["解压", "unzip", "extract"],
        "command_templates": ["tar -xzf archive.tar.gz", "unzip archive.zip"],
        "tips": ["解压前可用 tar -tzf 或 unzip -l 预览内容"],
    },
    {
        "category": "package_manager",
        "intent": "查询或安装系统软件包",
        "patterns": ["安装", "包", "apt", "yum", "dnf", "package"],
        "command_templates": ["sudo apt install <package>", "sudo yum install <package>"],
        "tips": ["安装命令会修改系统环境，应确认来源和包名"],
    },
    {
        "category": "package_manager",
        "intent": "查询 Python 或 Node 包",
        "patterns": ["pip", "npm", "python package", "node package"],
        "command_templates": ["pip show <package>", "npm list <package>"],
        "tips": ["全局安装可能影响当前开发环境"],
    },
]

